/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodo_biseccion;

import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dennis
 */
public class Ventana_P extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_P
     */
    Funcion f;
    private int i;
    public Ventana_P() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel_graficador = grafica.obtenerGrafica() ;
        jLabel1 = new javax.swing.JLabel();
        Campo_X0 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Campo_X1 = new javax.swing.JFormattedTextField();
        Tolerancia_txt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Campo_raiz = new javax.swing.JFormattedTextField();
        Campo_tolerancia = new javax.swing.JFormattedTextField();
        Graficar_X0 = new javax.swing.JFormattedTextField();
        Graficar_Xn = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Graficar_Intervalo = new javax.swing.JFormattedTextField();
        btn_graficar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_Calcular = new javax.swing.JButton();
        btn_creditos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodo de Bisección");
        setBackground(new java.awt.Color(102, 102, 102));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(65, 39, 214));
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setName("Ventana_P"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Panel_graficadorLayout = new javax.swing.GroupLayout(Panel_graficador);
        Panel_graficador.setLayout(Panel_graficadorLayout);
        Panel_graficadorLayout.setHorizontalGroup(
            Panel_graficadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        Panel_graficadorLayout.setVerticalGroup(
            Panel_graficadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Función");

        Campo_Fnc.setDoubleBuffered(true);
        Campo_Fnc.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Campo_Fnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_FncActionPerformed(evt);
            }
        });

        Campo_X0.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("X0");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("X1");

        Campo_X1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Campo_X1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_X1ActionPerformed(evt);
            }
        });

        Tolerancia_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Tolerancia_txt.setText("Tolerancia");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Raíz");

        Campo_raiz.setEditable(false);
        Campo_raiz.setDoubleBuffered(true);
        Campo_raiz.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Campo_raiz.setMaximumSize(new java.awt.Dimension(4, 28));

        Campo_tolerancia.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Campo_tolerancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campo_toleranciaActionPerformed(evt);
            }
        });

        Graficar_X0.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Graficar_Xn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("X0");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Xn");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Intervalo");

        Graficar_Intervalo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btn_graficar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_graficar.setText("Graficar");
        btn_graficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_graficarMouseClicked(evt);
            }
        });
        btn_graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
        });
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_Calcular.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_Calcular.setText("Calcular");
        btn_Calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CalcularMouseClicked(evt);
            }
        });
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        btn_creditos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_creditos.setText("Creditos");
        btn_creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_creditosMouseClicked(evt);
            }
        });
        btn_creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_creditosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_creditos)
                        .addGap(523, 523, 523)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Campo_Fnc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(Campo_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Campo_X0, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Graficar_X0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Graficar_Xn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(48, 48, 48)
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Graficar_Intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btn_graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(57, 57, 57))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Tolerancia_txt)
                                                        .addGap(33, 33, 33)
                                                        .addComponent(Campo_tolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(Campo_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(49, 49, 49)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addComponent(btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(164, 164, 164))))
                            .addComponent(Panel_graficador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_creditos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Campo_Fnc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tolerancia_txt)
                    .addComponent(Campo_tolerancia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Graficar_X0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Graficar_Xn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Campo_X0, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(Campo_raiz, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Graficar_Intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_graficar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Campo_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Calcular)
                            .addComponent(btn_cancelar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(Panel_graficador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_creditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_creditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_creditosActionPerformed

/*     
* Este evento de accionn capturado (btn_creditos)es para mostrar los creditos  
* donde aparecen los integrantes del proyecto realizado
*/
    
    private void btn_creditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creditosMouseClicked
        JOptionPane.showMessageDialog(null," Dennis Ariel Aké lópez 6329\n Diego Alejandro Ac Kantún 6220\n Alex Antonio Naal Ac 6230 \n Jose Alberto Dzib Brito 6235");
    }//GEN-LAST:event_btn_creditosMouseClicked

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        String definicion = Campo_Fnc.getText();							// Se extrae un string del campo donde se inserta la función
        double X0= Double.parseDouble(Campo_X0.getText());					
        double X1= Double.parseDouble(Campo_X1.getText());					// En estas variables el String obtenido de los campos
        double tol= Double.parseDouble(Campo_tolerancia.getText());		    // se convierten a Double y se incluyen en una variable del
        																	// mismo tipo
        Funcion fnc = new Funcion(definicion);							
        Biseccion b = new Biseccion(fnc);

        //double iteraciones= b.iteraciones(X0,X1,tol);
        //String txt_iteraciones = String.valueOf(iteraciones);				// Esta seccion era para hacer un contador
        //        Campo_iteraciones.setText(txt_iteraciones);				// no se implemento al final

        double r; 						//la instancia creada (b) de la clase biseccion y los metodos implementados en ella
        r = b.raiz(X0, X1, tol);		// añaden a la variable r de tipo double para hacer el formato y recorte de los decimales 
        String formato = "##.######";	// del resultado del metodo Bisección

        DecimalFormat decimalFormat = new DecimalFormat(formato); 
        String resultado_F;											// Toda esta seccion tambien es parte del tratamiento que se le
        resultado_F = decimalFormat.format(r);						// hace al resultado para darle formato y recortar decimales

        //double rgrados;
        //rgrados = Math.toDegrees(r);

        String resultado = resultado_F;
        Campo_raiz.setText(resultado);

    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void btn_CalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CalcularMouseClicked
        //String definición =fnc_eval.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CalcularMouseClicked

    private void btn_graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficarActionPerformed

    }//GEN-LAST:event_btn_graficarActionPerformed

    private void btn_graficarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_graficarMouseClicked
       try {                                                                    // El try catch es para controlar las excepciones que ocurran durante la captura de los datos del graficador
            String def = Campo_Fnc.getText();                                   // Se crea una variable de tipo string que recibe un dato del campo Funcion
            double x0=Double.parseDouble(Graficar_X0.getText());        
            double xn= Double.parseDouble(Graficar_Xn.getText());               // Creacion de una variable tipo double con el metodo de captura del string anidado en el metodo para convertirlo a Double parseDouble()
            double d= Double.parseDouble(Graficar_Intervalo.getText());
            Funcion fnc = new Funcion(def);                                     // Se crea un objeto de la clase Funcion al cual se le ingresa como parametro el String obtenido del campo Funcion (Campo_fnc)
            double[] x = fnc.rango(x0, xn, d);                                  // Se crea una arreglo del objeto fnc  el cual sera el eje X, ademas se le aplica el metodo rango() para guardar los parametros de entrada mientras se evalua la funcion
            double[] y = fnc.evaluar(x);                                        // se crea un arreglo para el eje Y el cual servira para guardar los valores evaluados de la funcion
            grafica.crearGrafica(def, x, y);                                    // al objeto grafica se le aplica el metodo con las variables de entrada creadas anteiormente (arreglos X Y y el string con la funcion)
        } catch (Exception ex) {
            Logger.getLogger(Ventana_P.class.getName()).log(Level.SEVERE, null, ex); //excepcion sugerida por Netbeans
        }
    }//GEN-LAST:event_btn_graficarMouseClicked

    private void Campo_FncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_FncActionPerformed

    }//GEN-LAST:event_Campo_FncActionPerformed

    private void Campo_X1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_X1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_X1ActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        Campo_Fnc.setText(" ");
        Campo_X0.setText(" ");
        Campo_X1.setText(" ");
        Campo_tolerancia.setText(" ");
        Campo_raiz.setText(" ");
        //     Campo_iteraciones.setText(" ");
        Graficar_X0.setText(" ");
        Graficar_Intervalo.setText(" ");
        Graficar_Xn.setText(" ");
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        // TODO add your handling code here:

        //metodo para limpiar todos los campos
    }//GEN-LAST:event_btn_cancelarMouseClicked

    private void Campo_toleranciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campo_toleranciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Campo_toleranciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JFormattedTextField Campo_Fnc = new javax.swing.JFormattedTextField();
    private javax.swing.JFormattedTextField Campo_X0;
    private javax.swing.JFormattedTextField Campo_X1;
    private javax.swing.JFormattedTextField Campo_raiz;
    private javax.swing.JFormattedTextField Campo_tolerancia;
    private javax.swing.JFormattedTextField Graficar_Intervalo;
    private javax.swing.JFormattedTextField Graficar_X0;
    private javax.swing.JFormattedTextField Graficar_Xn;
    public javax.swing.JPanel Panel_graficador;
    private javax.swing.JLabel Tolerancia_txt;
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_creditos;
    private javax.swing.JButton btn_graficar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
    Graficador grafica = new Graficador("Metodo de Biseccion","x","y");  // Se instancia un nuevo objeto de la clase Graficador
                                                                         // este objeto (grafica) se usara en las acciones del boton graficar
}                                                                    
